### ISSUE TITLE
Data package?

### ISSUE THREAD

**Issue by coatless** [daviddalpiaz/data#1]
How about structuring this into a data package ala:

https://github.com/coatless/uiucdata
or
https://github.com/coatless/ucidata

**Comment by daviddalpiaz** [comment]
Didn't you write a blog post somewhere about the size limitations of R packages? (Am I going crazy? I can't find it? Was it a SO post maybe?) I'm not saying this is going to become "big" but maybe!

**Comment by coatless** [comment]
@daviddalpiaz I did! In fact, it was a series that I thought I lost when I had to rebuild my webserver. I just reactivated the pages. (Links attached at the end.)

With this being said,  avoid conflating an _R_ package with being listed on _CRAN_. In the last article, I used a custom deployment strategy with `drat`. This allowed for the construction and inclusion of a package that had **over 50 MB** of data! Nowadays, this can be skipped if there is no _CRAN_ package that depends on the data by having users install the package with `remotes::install_github()`... 

(Fun trivia: I should have pushed to publish in a _journal_. I lost out on this to [Dirk & Brooke](https://journal.r-project.org/archive/2017/RJ-2017-026/index.html) as `Additional_repositories` was largely an undocumented feature at the time.)

Original series c.f. 
- [Size and Limitations of Packages on CRAN](http://thecoatlessprofessor.com/programming/size-and-limitations-of-packages-on-cran/)
- [Creating an R Data Package](http://thecoatlessprofessor.com/programming/creating-an-r-data-package/)
- [R Data Packages in External Data Repositories using the Additional_repositories field](http://thecoatlessprofessor.com/programming/r-data-packages-in-external-data-repositories-using-the-additional_repositories-field/)

**Comment by coatless** [comment]
Also, I'm toying around with releasing a design pattern package for _R_.

https://github.com/r-pkg-examples/pkgdesign

I'm having trouble justifying the idea though given that [`usethis`](https://usethis.r-lib.org/) and [`RStudio Package Templates`](https://rstudio.github.io/rstudio-extensions/rstudio_project_templates.html) exist.

**Comment by daviddalpiaz** [comment]
Finally merged your PR. Should I rename this package to `dalpiaz` if it might be for more than data as you wrote in the `README`?

**Comment by coatless** [comment]
@daviddalpiaz the name of the package is `dalpiaz`?

https://github.com/daviddalpiaz/data/blob/ddb48679dcf3aeb1acfc91318ebde2c07ad743ab/DESCRIPTION#L1-L2

I think you mean rename the repository?

**Comment by daviddalpiaz** [comment]
yeah that's what i meant

**Comment by coatless** [comment]
Yeah, go for it! Change `data` -> `dalpiaz`.
